apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-trhbnkug 
  janus-idp.io/tekton: go-trhbnkug
  backstage.io/kubernetes-id: go-trhbnkug
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-trhbnkug
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml